name: build mosaic python
description: build mosaic python
runs:
  using: "composite"
  steps:
    - name: Configure python interpreter
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install python dependencies
      shell: bash
      run: |
        # - install pip libs
        #   note: gdal requires the extra args
        cd python
        pip install build wheel pyspark==${{ matrix.spark }} numpy==${{ matrix.numpy }}
        pip install --no-build-isolation --no-cache-dir --force-reinstall gdal==${{ matrix.gdal }}
        pip install .
    - name: Give Python interpreter write access to checkpointing / raster write location
      shell: bash
      run: |
        sudo mkdir -p /mnt/mosaic_tmp
        sudo chmod -R 777 /mnt/mosaic_tmp
    - name: Test and build python package
      shell: bash
      run: |
        cd python
        python -m unittest
        python -m build
    - name: Copy python artifacts to GH Actions run
      shell: bash
      run: cp python/dist/*.whl staging